Repository HuckathonteamD/chat-app-next-2.0, pull requests merged in 2022-12, with the labels that each got.

#3 暗号化使用文字列を環境変数で実装。チャンネル表示順変更
  app.py
  k.txt
  models.py
  util/crypto_dec.py
Labels: BackEnd

#5 Feature#4　チャンネル一覧表示のバックエンドコードを修正
  static/js/pagination.js
Labels: BackEnd

#7 チャット画面で、followerの数を表示
  .vscode/settings.json
  app.py
  models.py
  static/css/chatroom.css
  templates/detail.html
Labels: FrontEnd, BackEnd

#10 Feature#2
  static/css/home.css
  static/js/pagination.js
  templates/index.html
Labels: FrontEnd

#12 非同期通信でのメッセージ表示の追加
  app.py
  static/css/detail.css
  static/css/modal.css
  static/js/chat-fetch.js
  static/js/detail-modal.js
  static/js/scroll-message.js
  templates/detail.html
  templates/modal/add-reaction-fetch.html
Labels: BackEnd

#14 MyPage修正しました
  static/css/home.css
  static/css/login.css
  static/css/my_page.css
  static/css/sign-up.css
  templates/index.html
  templates/my_page.html
  templates/registration/login.html
Labels: FrontEnd

#22 ログイン画面のレスポンシブ対応の実装
  static/css/login.css
  templates/registration/login.html
Labels: FrontEnd
